site_name: FruitNanny
repo_name: GitHub
repo_url: https://github.com/fruitnanny/fruitnanny-website
nav:
    - index.md
    - repository.md
    - crafting.md
    - api.md
    - ui.md
theme:
  name: material
  favicon: images/favicon.png
  icon:
    logo: material/camera-iris
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  # - git-revision-date-localized
  - toc:
      permalink: true