site_name: FruitNanny
site_url: https://fruitnanny.github.io/
repo_name: GitHub
repo_url: https://github.com/fruitnanny/fruitnanny.github.io/
edit_uri: edit/source/docs
copyright: Copyright © 2020 Lucas Kahlert  # Also change in "home.html"
nav:
  - index.md
  - User Guide:
     - user/getting-started.md
     - user/network.md
     - user/updates.md
  - Crafting Guide:
     - crafting.md
     - setup.md
  - Development Guide:
    - development/api.md
    - development/ui.md
theme:
  name: material
  favicon: images/favicon.png
  custom_dir: overrides
  icon:
    logo: material/camera-iris
  features:
    - tabs
  palette:
    primary: blue
    accent: pink
extra_css:
  - css/extra.css
plugins:
  - git-revision-date-localized
  - search
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - toc:
      permalink: true
